spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://localhost:3306/mdabang?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul
    username: root
    password: 9845cbJ!
    driver-class-name: com.mysql.cj.jdbc.Driver
  #    url: jdbc:mysql://localhost:3306/api?useSSL=false&serverTimezone=Asia/Seoul
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
server:
  port: 8080
